# Generated by Django 3.2.7 on 2021-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
