# Generated by Django 3.2.7 on 2021-11-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211117_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article_text',
            field=models.TextField(max_length=5000),
        ),
    ]
